version: '3'
services:
  circom:
    image: naps62/circom:latest
    container_name: circom-dev
    # build:
    #   context: .
    env_file:
      - .env
    ports:
      - 8888:8888
    volumes:
      - ./srv:/srv
    command: ["sh"]
    working_dir: /srv
    stdin_open: true # docker run -i
    tty: true        # docker run -t