version: '3'
services:
  circom:
    build:
      dockerfile: ./Docker/Dockerfile
    #image: naps62/circom:0.2.0
    image: cairo-circom:latest
    container_name: circom-dev
    # build:
    #   context: .
    env_file:
      - .env
    ports:
      - 8888:8888
      - 8545:8545
    volumes:
      - ./srv:/srv
    command: ["sh"]
    working_dir: /srv
    stdin_open: true # docker run -i
    tty: true        # docker run -t